name: CI for Auth Service

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      # 태그명 변수화 + 짧게 만들기
      - name: Set Image Version Tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Docker Image 빌드 및 푸시
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            pitterpetter/auth-service:${{ steps.vars.outputs.sha_short }}
            pitterpetter/auth-service:latest
      # IMAGE_NAME : prefix로 Docker Hub의 Repository 이름이 들어가야 함

      # ArgoCD가 참조하는 Repository로 checkout
      - name: Update Manifest Repo
        uses: actions/checkout@v3
        with:
          repository: PitterPetter/PitterPatter-Manifest    # ArgoCD가 바라보는 Organization/Repo
          token: ${{ secrets.GH_PAT }}       # Personal Access Token 필요
          path: manifests

      # Manifest Repository에서 Manifest 파일 내의 이미지 태그를 업데이트
      - name: Update image tag in Deployment yaml
        run: |
          cd manifests/charts/loventure
          # values.yaml 파일에서 auth-service 섹션의 tag 값만 업데이트
          sed -i '/^auth-service:/,/^[a-zA-Z]/ { /tag:/ s|tag: .*|tag: ${{ steps.vars.outputs.sha_short }}| }' values.yaml
          git config user.name "llokr1"
          git config user.email "ghdwlsrl100@gachon.ac.kr"
          git add values.yaml
          git commit -m "Update auth-service image to ${{ github.sha }}"
          git push origin main